### ISSUE TITLE
アクセスが拒否されました

### ISSUE THREAD

**Issue by Tsuyoshys** [hashimototakuya/cake_tutorial#1]
git@github.com:hayatravis/cake_tutorial.git
でクローンを作ろうとしたのですが、
Cloning into 'cake_tutorial'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
のエラーが出てクローンができませんでした。

**Comment by hashimototakuya** [comment]
返答遅れました。
クローン先を変更したので確認してみてください。
